### ISSUE TITLE
IllegalArgumentException with certain dependencies

### ISSUE THREAD

**Issue by adolski** [ImmobilienScout24/illegal-transitive-dependency-check#30]
Hi,

I've been using this plugin for a while and it's been working well. Thank you for developing it and making it available.

I recently pulled a couple of new dependencies into my project, and afterwards the illegal-transitive-dependency-check plugin started to throw an IllegalArgumentException. I've attempted to create an [SSCCE](https://github.com/adolski/illegal-transitive-dependency-check-exception-sscce) with one of the offending dependencies. I don't know enough about Maven to be able to fix it myself, unfortunately.

The error looks like:

`$ mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V -X`

```
Apache Maven 3.5.0 (ff8f5e7444045639af65f6095c62210b5713f426; 2017-04-03T14:39:06-05:00)
Maven home: /usr/local/Cellar/maven/3.5.0/libexec
Java version: 1.8.0_144, vendor: Oracle Corporation
Java home: /Library/Java/JavaVirtualMachines/jdk1.8.0_144.jdk/Contents/Home/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "mac os x", version: "10.13.1", arch: "x86_64", family: "mac"


......


[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 16.257 s
[INFO] Finished at: 2017-11-06T10:42:26-06:00
[INFO] Final Memory: 41M/432M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce) on project MyProject: Execution enforce of goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce failed. IllegalArgumentException -> [Help 1]
org.apache.maven.lifecycle.LifecycleExecutionException: Failed to execute goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce (enforce) on project MyProject: Execution enforce of goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce failed.
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:213)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:154)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:146)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:117)
	at org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject(LifecycleModuleBuilder.java:81)
	at org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build(SingleThreadedBuilder.java:51)
	at org.apache.maven.lifecycle.internal.LifecycleStarter.execute(LifecycleStarter.java:128)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:309)
	at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:194)
	at org.apache.maven.DefaultMaven.execute(DefaultMaven.java:107)
	at org.apache.maven.cli.MavenCli.execute(MavenCli.java:993)
	at org.apache.maven.cli.MavenCli.doMain(MavenCli.java:345)
	at org.apache.maven.cli.MavenCli.main(MavenCli.java:191)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced(Launcher.java:289)
	at org.codehaus.plexus.classworlds.launcher.Launcher.launch(Launcher.java:229)
	at org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode(Launcher.java:415)
	at org.codehaus.plexus.classworlds.launcher.Launcher.main(Launcher.java:356)
Caused by: org.apache.maven.plugin.PluginExecutionException: Execution enforce of goal org.apache.maven.plugins:maven-enforcer-plugin:1.3.1:enforce failed.
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:145)
	at org.apache.maven.lifecycle.internal.MojoExecutor.execute(MojoExecutor.java:208)
	... 20 more
Caused by: java.lang.IllegalArgumentException
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at org.objectweb.asm.ClassReader.<init>(Unknown Source)
	at de.is24.maven.enforcer.rules.ArtifactRepositoryAnalyzer.analyzeJar(ArtifactRepositoryAnalyzer.java:76)
	at de.is24.maven.enforcer.rules.ArtifactRepositoryAnalyzer.analyzeArtifacts(ArtifactRepositoryAnalyzer.java:51)
	at de.is24.maven.enforcer.rules.IllegalTransitiveDependencyCheck.execute(IllegalTransitiveDependencyCheck.java:115)
	at org.apache.maven.plugins.enforcer.EnforceMojo.execute(EnforceMojo.java:177)
	at org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo(DefaultBuildPluginManager.java:134)
	... 21 more
```

**Comment by kinow** [comment]
The issue seems to be at ASM.

* Checked out the SSCCE example, and reproduced the issue with `mvn clean verify`
* Checked out illegal-transitive-dependency-check, which is 1.8-SNAPSHOT
* Updated asm to 6.0 in pom, and did a `mvn clean install -DskipTests`
* Updated the SCCEE example to use the local version of the plug-in, 0.8-SNAPSHOT
* `mvn clean verify` worked

So I guess it's just class compatibility? The plug-in fails when parsing .m2/repository/org/eclipse/jetty/jetty-alpn-java-client/9.4.7.v20170914/jetty-alpn-java-client-9.4.7.v20170914.jar FWIW

Hope that helps
Bruno
